# NumPy DataTypes and Attributes

In [1]:
import numpy as np

## NumPy's main datatype is ndarray

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array(
    [
        [1.8, 2, 3.6],
        [4.0, 5, 6.1]
    ]
)

a2

array([[1.8, 2. , 3.6],
       [4. , 5. , 6.1]])

In [5]:
a3 = np.array(
    [
        [
            [1, 2, 3],
            [3, 4, 5],
            [6, 7, 8]
        ],
        [
            [10 ,11, 12],
            [13, 14, 15],
            [16, 17, 18]
        ]
    ],
    dtype=np.int16
)
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int16)

In [6]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 3, 3)


In [7]:
a1.ndim, a2.ndim, a3.ndim,

(1, 2, 3)

In [8]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int16'))

In [9]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [10]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a DataFrame form a NumPy Array

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.8  2.0  3.6
1  4.0  5.0  6.1

# Creating NumPy Arrays

In [13]:
ones = np.ones(2)
ones

array([1., 1.])

In [14]:
ones.dtype

dtype('float64')

In [15]:
ones = np.ones(shape=(2,3), dtype=np.int16)
ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [16]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array = np.arange(start=0,stop=10,step=2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array = np.random.randint(low=0, high=10, size=(3,5))
random_array

array([[9, 0, 3, 3, 1],
       [3, 5, 9, 1, 2],
       [9, 5, 3, 6, 3]])

In [19]:
np.random.random(size=(5,5))

array([[0.52638848, 0.80164068, 0.4093217 , 0.13867717, 0.12359496],
       [0.21052384, 0.02827283, 0.50067322, 0.6009405 , 0.78950455],
       [0.2399646 , 0.80881973, 0.37624134, 0.9477892 , 0.81133577],
       [0.0499778 , 0.54992492, 0.19832556, 0.26669774, 0.55581752],
       [0.69171348, 0.46047397, 0.52221294, 0.01649138, 0.43109193]])

In [20]:
np.random.rand(2,3)

array([[0.05944082, 0.28194764, 0.12005489],
       [0.57696638, 0.97305431, 0.40916369]])

# NumPy Random Seed

## Pseudo random numbers

In [21]:
np.random.seed(seed=0)
np.random.randint(10, size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [22]:
np.random.seed(seed=0)
np.random.randint(10, size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [23]:
np.random.randint(10, size=(5,3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [24]:
np.random.seed(5)
np.random.random((5, 3)) 

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703]])

# Viewing Arrays and Matrices

In [28]:
random_array = np.random.randint(0,10,(3,3))
random_array

array([[4, 9, 3],
       [2, 4, 6],
       [9, 3, 3]])

In [36]:
np.unique(random_array)

array([2, 3, 4, 6, 9])

In [38]:
a1[0]

1

In [39]:
a2[0]

array([1.8, 2. , 3.6])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int16)

In [52]:
a3[0]

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

In [55]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 11],
        [13, 14]]], dtype=int16)

In [57]:
a3[:,:,:2]

array([[[ 1,  2],
        [ 3,  4],
        [ 6,  7]],

       [[10, 11],
        [13, 14],
        [16, 17]]], dtype=int16)