# NumPy DataTypes and Attributes

In [1]:
import numpy as np

## NumPy's main datatype is ndarray

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array(
    [
        [1.8, 2, 3.6],
        [4.0, 5, 6.1]
    ]
)

a2

array([[1.8, 2. , 3.6],
       [4. , 5. , 6.1]])

In [5]:
a3 = np.array(
    [
        [
            [1, 2, 3],
            [3, 4, 5],
            [6, 7, 8]
        ],
        [
            [10 ,11, 12],
            [13, 14, 15],
            [16, 17, 18]
        ]
    ],
    dtype=np.int16
)
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int16)

In [6]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 3, 3)


In [7]:
a1.ndim, a2.ndim, a3.ndim,

(1, 2, 3)

In [8]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int16'))

In [9]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [10]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a DataFrame form a NumPy Array

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.8  2.0  3.6
1  4.0  5.0  6.1

# Creating NumPy Arrays

In [15]:
ones = np.ones(2)
ones

array([1., 1.])

In [16]:
ones.dtype

dtype('float64')

In [14]:
ones = np.ones(shape=(2,3), dtype=np.int16)
ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [17]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(start=0,stop=10,step=2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(low=0, high=10, size=(3,5))
random_array

array([[7, 5, 5, 7, 9],
       [0, 6, 0, 7, 7],
       [2, 5, 5, 6, 3]])

In [22]:
np.random.random(size=(5,5))

array([[0.3367005 , 0.17505051, 0.82087142, 0.96536322, 0.34094422],
       [0.65224095, 0.98195555, 0.50584256, 0.5971193 , 0.17546681],
       [0.88550191, 0.6837436 , 0.26447631, 0.70972237, 0.63560594],
       [0.64585878, 0.43748119, 0.92922551, 0.7422982 , 0.59160897],
       [0.47576109, 0.99825157, 0.99579828, 0.6640952 , 0.04120843]])

In [24]:
np.random.rand(2,3)

array([[0.32491664, 0.70057732, 0.4258745 ],
       [0.49207288, 0.23211732, 0.30314292]])

# NumPy Random Seed

## Pseudo random numbers

In [43]:
np.random.seed(seed=0)
np.random.randint(10, size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [44]:
np.random.seed(seed=0)
np.random.randint(10, size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [46]:
np.random.randint(10, size=(5,3))

array([[2, 3, 8],
       [1, 3, 3],
       [3, 7, 0],
       [1, 9, 9],
       [0, 4, 7]])

In [57]:
np.random.seed(5)
np.random.random((5, 3)) 

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703]])