# NumPy DataTypes and Attributes

In [2]:
import numpy as np

## NumPy's main datatype is ndarray

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array(
    [
        [1.8, 2, 3.6],
        [4.0, 5, 6.1]
    ]
)

a2

array([[1.8, 2. , 3.6],
       [4. , 5. , 6.1]])

In [16]:
a3 = np.array(
    [
        [
            [1, 2, 3],
            [3, 4, 5],
            [6, 7, 8]
        ],
        [
            [10 ,11, 12],
            [13, 14, 15],
            [16, 17, 18]
        ]
    ],
    dtype=np.int16
)
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int16)

In [17]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 3, 3)


In [18]:
a1.ndim, a2.ndim, a3.ndim,

(1, 2, 3)

In [19]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int16'))

In [20]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [21]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a DataFrame form a NumPy Array

In [22]:
import pandas as pd

In [23]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.8  2.0  3.6
1  4.0  5.0  6.1