# NumPy DataTypes and Attributes

In [1]:
import numpy as np

## NumPy's main datatype is ndarray

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array(
    [
        [1.8, 2, 3.6],
        [4.0, 5, 6.1]
    ]
)

a2

array([[1.8, 2. , 3.6],
       [4. , 5. , 6.1]])

In [5]:
a3 = np.array(
    [
        [
            [1, 2, 3],
            [3, 4, 5],
            [6, 7, 8]
        ],
        [
            [10 ,11, 12],
            [13, 14, 15],
            [16, 17, 18]
        ]
    ],
    dtype=np.int16
)
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int16)

In [6]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 3, 3)


In [7]:
a1.ndim, a2.ndim, a3.ndim,

(1, 2, 3)

In [8]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int16'))

In [9]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [10]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## Create a DataFrame form a NumPy Array

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.8  2.0  3.6
1  4.0  5.0  6.1

# Creating NumPy Arrays

In [13]:
ones = np.ones(2)
ones

array([1., 1.])

In [14]:
ones.dtype

dtype('float64')

In [15]:
ones = np.ones(shape=(2,3), dtype=np.int16)
ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [16]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array = np.arange(start=0,stop=10,step=2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array = np.random.randint(low=0, high=10, size=(3,5))
random_array

array([[4, 6, 7, 4, 3],
       [1, 6, 5, 0, 5],
       [5, 6, 4, 7, 1]])

In [19]:
np.random.random(size=(5,5))

array([[5.79707549e-01, 9.07962975e-01, 4.41678238e-01, 8.53225368e-01,
        3.46462731e-01],
       [2.39592617e-01, 6.38471049e-01, 3.79285755e-01, 6.57546656e-01,
        7.39659735e-01],
       [3.33280309e-01, 1.65495017e-02, 4.51063076e-01, 9.94463719e-01,
        6.07698094e-01],
       [3.30197025e-01, 2.45791020e-01, 4.62550453e-02, 1.93882451e-01,
        4.33175851e-04],
       [1.88432953e-01, 9.31841291e-01, 7.65660130e-01, 9.94955900e-01,
        6.41637281e-01]])

In [20]:
np.random.rand(2,3)

array([[0.17853674, 0.35935591, 0.14338479],
       [0.99978761, 0.11701667, 0.48792675]])

# NumPy Random Seed

## Pseudo random numbers

In [21]:
np.random.seed(seed=0)
np.random.randint(10, size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [22]:
np.random.seed(seed=0)
np.random.randint(10, size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [23]:
np.random.randint(10, size=(5,3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [24]:
np.random.seed(5)
np.random.random((5, 3)) 

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ],
       [0.44130922, 0.15830987, 0.87993703]])

# Viewing Arrays and Matrices

In [25]:
random_array = np.random.randint(0,10,(3,3))
random_array

array([[4, 6, 2],
       [9, 9, 9],
       [9, 1, 2]])

In [26]:
np.unique(random_array)

array([1, 2, 4, 6, 9])

In [27]:
a1[0]

1

In [28]:
a2[0]

array([1.8, 2. , 3.6])

In [29]:
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int16)

In [30]:
a3[0]

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

In [31]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 3,  4]],

       [[10, 11],
        [13, 14]]], dtype=int16)

In [32]:
a3[:,:,:2]

array([[[ 1,  2],
        [ 3,  4],
        [ 6,  7]],

       [[10, 11],
        [13, 14],
        [16, 17]]], dtype=int16)

# Manipulating Arrays

## Arithmetic

In [33]:
a1

array([1, 2, 3])

In [36]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [37]:
a1 + ones

array([2., 3., 4.])

In [38]:
a1 - ones

array([0., 1., 2.])

In [39]:
a1 * ones

array([1., 2., 3.])

In [40]:
a1

array([1, 2, 3])

In [42]:
a2

array([[1.8, 2. , 3.6],
       [4. , 5. , 6.1]])

In [47]:
a1 * a2

array([[ 1.8,  4. , 10.8],
       [ 4. , 10. , 18.3]])

In [48]:
a1.shape, a2.shape

((3,), (2, 3))

In [ ]:
# (2, 3)
# ( , 3)

In [50]:
a3*a1

array([[[ 1,  4,  9],
        [ 3,  8, 15],
        [ 6, 14, 24]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [51]:
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int16)

In [56]:
a4 = np.ones(shape=(3,3))*2
a4

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [57]:
a3*a4

array([[[ 2.,  4.,  6.],
        [ 6.,  8., 10.],
        [12., 14., 16.]],

       [[20., 22., 24.],
        [26., 28., 30.],
        [32., 34., 36.]]])

In [58]:
a3.shape, a4.shape

((2, 3, 3), (3, 3))

In [ ]:
# (2, 3, 3) 
# ( , 3, 3)

In [61]:
print(a1)
print(ones)
a1/ones

[1 2 3]
[1. 1. 1.]


array([1., 2., 3.])

In [64]:
print(a2)
print(a1)
# floor division remove the decimal (rounds down)
print(a2 / a1)
print(a2 // a1)

[[1.8 2.  3.6]
 [4.  5.  6.1]]
[1 2 3]
[[1.8        1.         1.2       ]
 [4.         2.5        2.03333333]]
[[1. 1. 1.]
 [4. 2. 2.]]


In [67]:
print(a1)
print(a1 ** 2)
print(np.square(a1))

[1 2 3]
[1 4 9]
[1 4 9]


In [68]:
np.add(a1, ones)

array([2., 3., 4.])

In [69]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [70]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [71]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])