# Introduction to tensors

## Importing Tensorflow

In [1]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.5.0


## Create tensors with `tf.constant()`

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

### Check number of dimensions

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>, 1)

In [ ]:
matrix = tf.constant(
    [
        [1, 2],
        [3, 4]
    ]
)
matrix, f'ndim = {matrix.ndim}'

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 'ndim = 2')

### Data type

In [ ]:
matrix2 = tf.constant(
    [
        [1.1, 2.],
        [3, 4.12],
        [5, 6]
    ],
    dtype=tf.float16
)
matrix2, f'ndim = {matrix2.ndim}'

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1.1 , 2.  ],
        [3.  , 4.12],
        [5.  , 6.  ]], dtype=float16)>,
 'ndim = 2')

In [ ]:
tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ]
    ]
)
tensor, f'ndim = {tensor.ndim}'

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]])>,
 'ndim = 3')

`All above are tensors (scalars, vectors, matrices)`

`Tensors can be n-dimensional`

## Create tensors with `tf.Variable()`

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [ ]:
changeable_tensor[0], unchangeable_tensor[0]

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>)

In [ ]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
unchangeable_tensor[0] = 7
unchangeable_tensor

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating random tensors

In [ ]:
# Create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffling the order of tensors

In [4]:
not_shuffled = tf.constant(
    [
        [10, 7],
        [3, 4],
        [2, 5]
    ]
)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [8]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [18]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [5]:
tf.random.set_seed(42) # global seed
tf.random.shuffle(not_shuffled, seed=42) # operation-level seeds

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [6]:
tf.random.set_seed(42) # global seed
tf.random.shuffle(not_shuffled, seed=42) # operation-level seeds

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### `https://www.tensorflow.org/api_docs/python/tf/random/set_seed`

## Creating tensors from NumPy arrays

### Ones and Zeros

In [25]:
tf.ones([5, 7], dtype=tf.int16)

<tf.Tensor: shape=(5, 7), dtype=int16, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int16)>

In [28]:
tf.zeros(shape=(5, 7))

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### NumPy to Tensor

#### The main difference between NumPy arrays and TensorFIow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [29]:
import numpy as np

In [30]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [40]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [42]:
2 * 3 * 4

24

In [43]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [44]:
A.ndim

3

## Getting information from your tensors (tensor attributes)

In [2]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [3]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [4]:
print(f'Shape : {rank_4_tensor.shape}\nRank or number of dimensions : {rank_4_tensor.ndim}\nSize : {tf.size(rank_4_tensor)}\nData type : {rank_4_tensor.dtype}')

Shape : (2, 3, 4, 5)
Rank or number of dimensions : 4
Size : 120
Data type : <dtype: 'float32'>


In [5]:
print(f'Elements along the 0 axix : {rank_4_tensor.shape[0]}')
print(f'Elements along the last axix : {rank_4_tensor.shape[-1]}')

Elements along the 0 axix : 2
Elements along the last axix : 5


## Indexing and expanding tensors

### Get the first two elements of each dimensions 

In [9]:
some_list = [1, 2, 3, 4, 5]
some_list[:2]

[1, 2]

In [7]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

### Get the first element form each dimension from each index except for the final one

In [17]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
rank_2_tensor = tf.constant(
    [
        [3, 7],
        [10, 4]
    ]
)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  7],
       [10,  4]])>

### Get the last item of each of row

In [22]:
rank_2_tensor[:,-1:], rank_2_tensor[:,-1]

(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[7],
        [4]])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>)

### Add in extra dimension

In [29]:
rank_2_tensor[...], rank_2_tensor[:, :]

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 3,  7],
        [10,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 3,  7],
        [10,  4]])>)

In [25]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[10],
        [ 4]]])>

In [28]:
tf.reshape(rank_2_tensor, shape=(2,2,1))

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[10],
        [ 4]]])>

In [30]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1 for expand the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[10],
        [ 4]]])>

In [32]:
tf.expand_dims(rank_2_tensor, axis=0) # 0 for expand the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 3,  7],
        [10,  4]]])>

## Manipulating tensors with basic operations

**Basic oparations**
( `+`, `-`, `*`, `/` )

In [3]:
tensor = tf.constant(
    [
        [10, 7],
        [3, 4]
    ]
)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [4]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [5]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [6]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [10]:
tf.math.multiply(tensor, 10), tf.multiply(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>)

In [9]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

## Matrix multiplication with tensors part 1

In [2]:
tensor = tf.constant(
    [
        [10, 7],
        [3, 4]
    ]
)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [6]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [5]:
tf.linalg.matmul(tensor, tensor), tf.matmul(tensor, tensor), tensor @ tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>)

In [7]:
x = tf.constant(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
)
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [9]:
x @ x

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [17]:
tf.transpose(x) @ x, x @ tf.transpose(x)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[35, 44],
        [44, 56]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])>)