---
# ***Introduction to tensors***
---

## Importing Tensorflow

In [1]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.5.0


## Create tensors with `tf.constant()`

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

### Check number of dimensions

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10, 10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>, 1)

In [ ]:
matrix = tf.constant(
    [
        [1, 2],
        [3, 4]
    ]
)
matrix, f'ndim = {matrix.ndim}'

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 'ndim = 2')

### Data type

In [ ]:
matrix2 = tf.constant(
    [
        [1.1, 2.],
        [3, 4.12],
        [5, 6]
    ],
    dtype=tf.float16
)
matrix2, f'ndim = {matrix2.ndim}'

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1.1 , 2.  ],
        [3.  , 4.12],
        [5.  , 6.  ]], dtype=float16)>,
 'ndim = 2')

In [ ]:
tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ]
    ]
)
tensor, f'ndim = {tensor.ndim}'

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]])>,
 'ndim = 3')

`All above are tensors (scalars, vectors, matrices)`

`Tensors can be n-dimensional`

## Create tensors with `tf.Variable()`

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [ ]:
changeable_tensor[0], unchangeable_tensor[0]

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>)

In [ ]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
unchangeable_tensor[0] = 7
unchangeable_tensor

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating random tensors

In [ ]:
# Create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffling the order of tensors

In [4]:
not_shuffled = tf.constant(
    [
        [10, 7],
        [3, 4],
        [2, 5]
    ]
)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [8]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [18]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [5]:
tf.random.set_seed(42) # global seed
tf.random.shuffle(not_shuffled, seed=42) # operation-level seeds

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [6]:
tf.random.set_seed(42) # global seed
tf.random.shuffle(not_shuffled, seed=42) # operation-level seeds

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### `https://www.tensorflow.org/api_docs/python/tf/random/set_seed`

## Creating tensors from NumPy arrays

### Ones and Zeros

In [25]:
tf.ones([5, 7], dtype=tf.int16)

<tf.Tensor: shape=(5, 7), dtype=int16, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int16)>

In [28]:
tf.zeros(shape=(5, 7))

<tf.Tensor: shape=(5, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### NumPy to Tensor

#### The main difference between NumPy arrays and TensorFIow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [29]:
import numpy as np

In [30]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [40]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [42]:
2 * 3 * 4

24

In [43]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [44]:
A.ndim

3

## Getting information from your tensors (tensor attributes)

In [2]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [3]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [4]:
print(f'Shape : {rank_4_tensor.shape}\nRank or number of dimensions : {rank_4_tensor.ndim}\nSize : {tf.size(rank_4_tensor)}\nData type : {rank_4_tensor.dtype}')

Shape : (2, 3, 4, 5)
Rank or number of dimensions : 4
Size : 120
Data type : <dtype: 'float32'>


In [5]:
print(f'Elements along the 0 axix : {rank_4_tensor.shape[0]}')
print(f'Elements along the last axix : {rank_4_tensor.shape[-1]}')

Elements along the 0 axix : 2
Elements along the last axix : 5


## Indexing and expanding tensors

### Get the first two elements of each dimensions 

In [9]:
some_list = [1, 2, 3, 4, 5]
some_list[:2]

[1, 2]

In [7]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

### Get the first element form each dimension from each index except for the final one

In [17]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
rank_2_tensor = tf.constant(
    [
        [3, 7],
        [10, 4]
    ]
)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  7],
       [10,  4]])>

### Get the last item of each of row

In [22]:
rank_2_tensor[:,-1:], rank_2_tensor[:,-1]

(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[7],
        [4]])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>)

### Add in extra dimension

In [29]:
rank_2_tensor[...], rank_2_tensor[:, :]

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 3,  7],
        [10,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 3,  7],
        [10,  4]])>)

In [25]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[10],
        [ 4]]])>

In [28]:
tf.reshape(rank_2_tensor, shape=(2,2,1))

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[10],
        [ 4]]])>

In [30]:
tf.expand_dims(rank_2_tensor, axis=-1) # -1 for expand the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[10],
        [ 4]]])>

In [32]:
tf.expand_dims(rank_2_tensor, axis=0) # 0 for expand the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 3,  7],
        [10,  4]]])>

## Manipulating tensors with basic operations

**Basic oparations**
( `+`, `-`, `*`, `/` )

In [3]:
tensor = tf.constant(
    [
        [10, 7],
        [3, 4]
    ]
)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [4]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [5]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [6]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [10]:
tf.math.multiply(tensor, 10), tf.multiply(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>)

In [9]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

## Matrix multiplication with tensors part 1

In [18]:
tensor = tf.constant(
    [
        [10, 7],
        [3, 4]
    ]
)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [19]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [20]:
tf.linalg.matmul(tensor, tensor), tf.matmul(tensor, tensor), tensor @ tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>)

## Matrix multiplication with tensors part 2

In [23]:
x = tf.constant(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
)
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [25]:
tf.reshape(x, shape=(2,3)), tf.transpose(x)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>)

In [22]:
tf.transpose(x) @ x, x @ tf.transpose(x)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[35, 44],
        [44, 56]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])>)

In [26]:
tf.reshape(x, shape=(2,3)) @ x, x @ tf.reshape(x, shape=(2,3))

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[22, 28],
        [49, 64]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])>)

## Matrix multiplication with tensors part 3

**Dot Product (Matrix multiplication)**
* `@`
* `tf.matmul()`
* `tf.tensordot()`

In [2]:
x = tf.constant(
    [
        [1, 2],
        [3, 4],
        [5, 6],
    ]
)

y = tf.constant(
    [
        [7, 8],
        [9, 10],
        [11,12],
    ]
)

x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [6]:
tf.transpose(x).shape, y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [5]:
tf.tensordot(tf.transpose(x), y, axes=1), tf.matmul(tf.transpose(x), y), tf.transpose(x) @ y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>)

## Changing the datatype of tensors

### Default datatypes

In [7]:
x = tf.constant([1.2, 14])
x.dtype

tf.float32

In [8]:
y = tf.constant([12, 14])
y.dtype

tf.int32

### Change the datatype

In [10]:
x = tf.cast(x, dtype=tf.float16)
x

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1.2, 14. ], dtype=float16)>

In [11]:
y = tf.cast(y, dtype=tf.float32)
y

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12., 14.], dtype=float32)>

## Tensor aggregation (finding the min, max, mean & more)

In [2]:
A = tf.constant([-7, -10])
A, tf.abs(A)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>)

### Create a random tensor

In [2]:
import numpy as np
x = tf.constant(np.random.randint(0, 100, size=50))
x

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([25, 55,  2, 29, 56, 64, 18, 94,  4, 62,  1,  7, 92,  9,  7,  6, 90,
        6, 49, 68, 14, 90, 87, 72, 34, 43, 48, 24, 93, 93, 45, 34, 36, 76,
        3, 73, 28, 50, 97, 50, 87, 86, 74,  5, 28, 59, 54, 71,  2, 64])>

### Find minimum

In [3]:
tf.reduce_min(x)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
tf.reduce_min(x).numpy()

1

In [5]:
type(tf.reduce_min(x).numpy())

numpy.int32

### Find maximum

In [6]:
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

### Find mean

In [7]:
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=int32, numpy=47>

### Find sum

In [8]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2364>

## Tensor troubleshooting example (updating tensor datatypes)

In [4]:
import numpy as np
x = tf.constant(np.random.randint(0, 100, size=50))
x

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([39, 99, 95, 73, 42, 65, 78, 75, 63, 18, 23, 47, 53, 38, 30, 29, 88,
       69, 53, 41, 36, 59,  1, 25, 25, 71, 48, 95, 96,  2,  8,  2,  4,  5,
       61, 77, 53, 25, 83, 15, 30, 96,  4, 49,  6, 39, 16, 12, 98, 66])>

### Standard deviation

In [5]:
tf.math.reduce_std(tf.cast(x, tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=30.2>

### Variance

In [6]:
tf.math.reduce_variance(tf.cast(x, tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=912.5>

In [7]:
tf.square(tf.math.reduce_std(tf.cast(x, tf.float16)))

<tf.Tensor: shape=(), dtype=float16, numpy=912.0>

## Finding the positional minimum and maximum of a tensor (argmin and argmax)

In [37]:
import numpy as np
x = tf.constant(np.random.randint(0, 100, size=50))
x

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 9, 66, 95, 84, 51, 74, 49, 73, 59, 62, 12, 38,  8, 88, 44, 20, 43,
       63, 24, 11, 88, 64, 22, 46, 57, 17, 85, 69, 96, 48, 57, 52, 16, 73,
       11, 10, 99, 55, 44, 99, 79, 88, 94, 65, 47,  3, 29,  4, 58, 55])>

In [38]:
tf.argmax(x), tf.argmax(x).numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=36>, 36)

In [39]:
maxIndex = tf.argmax(x)

In [40]:
x[maxIndex], x[maxIndex].numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=99>, 99)

In [41]:
f'Max index : {tf.argmax(x).numpy()}, Max value : {x[tf.argmax(x)].numpy()}'

'Max index : 36, Max value : 99'

In [42]:
f'Min index : {tf.argmin(x).numpy()}, Min value : {x[tf.argmin(x)].numpy()}'

'Min index : 45, Min value : 3'

## Squeezing a tensor (removing all 1-dimension axes)

In [4]:
x = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,1,50))
x

<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.5051892 , 0.3352226 , 0.03948772, 0.93859935,
            0.02069163, 0.6348798 , 0.20514369, 0.01114166,
            0.09206808, 0.36025894, 0.6410247 , 0.6864015 ,
            0.5868064 , 0.27557063, 0.74733865, 0.22603595,
            0.48203015, 0.81686544, 0.2428112 , 0.35271966,
            0.05942893, 0.7676281 , 0.5894134 , 0.43947017,
            0.13340008, 0.45562327, 0.43772304, 0.69461834,
            0.3510592 , 0.67967   , 0.3946805 , 0.3288554 ,
            0.44373417, 0.62452996, 0.729529  , 0.05121386,
            0.93530154, 0.00508499, 0.50011003, 0.04546404,
            0.7923341 , 0.08233535, 0.6629816 , 0.00171804,
            0.5609945 , 0.16197324, 0.69964194, 0.21466362,
            0.3913026 , 0.19087052]]]]]], dtype=float32)>

In [5]:
x.shape

TensorShape([1, 1, 1, 1, 1, 50])

In [7]:
x_squeeze = tf.squeeze(x)
x_squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.5051892 , 0.3352226 , 0.03948772, 0.93859935, 0.02069163,
       0.6348798 , 0.20514369, 0.01114166, 0.09206808, 0.36025894,
       0.6410247 , 0.6864015 , 0.5868064 , 0.27557063, 0.74733865,
       0.22603595, 0.48203015, 0.81686544, 0.2428112 , 0.35271966,
       0.05942893, 0.7676281 , 0.5894134 , 0.43947017, 0.13340008,
       0.45562327, 0.43772304, 0.69461834, 0.3510592 , 0.67967   ,
       0.3946805 , 0.3288554 , 0.44373417, 0.62452996, 0.729529  ,
       0.05121386, 0.93530154, 0.00508499, 0.50011003, 0.04546404,
       0.7923341 , 0.08233535, 0.6629816 , 0.00171804, 0.5609945 ,
       0.16197324, 0.69964194, 0.21466362, 0.3913026 , 0.19087052],
      dtype=float32)>

In [8]:
x_squeeze.shape

TensorShape([50])

## One-hot encoding tensors

In [11]:
some_list = [0, 1, 2, 3]

In [14]:
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [13]:
tf.one_hot(some_list, depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

### specify custom values for one hot encoding

In [15]:
tf.one_hot(some_list, depth=4, on_value='ON', off_value='OFF')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>