# Introduction to tensors

## Importing Tensorflow

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.5.0


## Create tensors with `tf.constant()`

In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

### Check number of dimensions

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10, 10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>, 1)

In [6]:
matrix = tf.constant(
    [
        [1, 2],
        [3, 4]
    ]
)
matrix, f'ndim = {matrix.ndim}'

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 'ndim = 2')

### Data type

In [7]:
matrix2 = tf.constant(
    [
        [1.1, 2.],
        [3, 4.12],
        [5, 6]
    ],
    dtype=tf.float16
)
matrix2, f'ndim = {matrix2.ndim}'

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1.1 , 2.  ],
        [3.  , 4.12],
        [5.  , 6.  ]], dtype=float16)>,
 'ndim = 2')

In [8]:
tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ]
    ]
)
tensor, f'ndim = {tensor.ndim}'

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]])>,
 'ndim = 3')

`All above are tensors (scalars, vectors, matrices)`

`Tensors can be n-dimensional`

## Create tensors with `tf.Variable()`

In [9]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [10]:
changeable_tensor[0], unchangeable_tensor[0]

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>)

In [11]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [12]:
unchangeable_tensor[0] = 7
unchangeable_tensor

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [13]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [14]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating random tensors 

In [18]:
# Create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)