# Introduction to tensors

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.5.0


## Create tensors with tf.constant()

In [15]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

### Check number of dimensions

In [16]:
scalar.ndim

0

In [10]:
vector = tf.constant([10, 10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>, 1)

In [20]:
matrix = tf.constant(
    [
        [1, 2],
        [3, 4]
    ]
)
matrix, f'ndim = {matrix.ndim}'

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 'ndim = 2')

### Data type

In [24]:
matrix2 = tf.constant(
    [
        [1.1, 2.],
        [3, 4.12],
        [5, 6]
    ],
    dtype=tf.float16
)
matrix2, f'ndim = {matrix2.ndim}'

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1.1 , 2.  ],
        [3.  , 4.12],
        [5.  , 6.  ]], dtype=float16)>,
 'ndim = 2')

In [26]:
tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ]
    ]
)
tensor, f'ndim = {tensor.ndim}'

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]])>,
 'ndim = 3')

`All above are tensors (scalars, vectors, matrices)`

`Tensors can be n-dimensional`